### ISSUE TITLE
Everything is pretty much....broken

### ISSUE THREAD

**Issue by opticoax747** [mandiant/flare-vm#267]
Seems I am using this to learn how to troubleshoot python rather than analyzing malware.

λ olemap.exe -x "f11b7237907275ca59ce4f0b630f69a6c3770b0060359917bf465690e2309e47 (1).bin"
olemap 0.54 - http://decalage.info/python/oletools
-------------------------------------------------------------------------------
FILE: f11b7237907275ca59ce4f0b630f69a6c3770b0060359917bf465690e2309e47 (1).bin

Traceback (most recent call last):
  File "C:\Python37\Scripts\olemap-script.py", line 11, in <module>
    load_entry_point('oletools==0.54.2', 'console_scripts', 'olemap')()
  File "C:\Python37\lib\site-packages\oletools-0.54.2-py3.7.egg\oletools\olemap.py", line 278, in main
    ole = olefile.OleFileIO(filename)
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1075, in __init__
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1192, in open
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1105, in _raise_defect
OSError: not an OLE2 structured storage file

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\oletools-0.54.2-py3.7.egg\oletools\olebrowse.py", line 133, in main
    ole = olefile.OleFileIO(filename)
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1075, in __init__
    self.open(filename, write_mode=write_mode)
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1192, in open
    self._raise_defect(DEFECT_FATAL, "not an OLE2 structured storage file")
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1105, in _raise_defect
    raise exception_type(message)
OSError: not an OLE2 structured storage file

λ olemeta.exe "f11b7237907275ca59ce4f0b630f69a6c3770b0060359917bf465690e2309e47 (1).bin"
olemeta 0.54 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues
===============================================================================
FILE: f11b7237907275ca59ce4f0b630f69a6c3770b0060359917bf465690e2309e47 (1).bin

Traceback (most recent call last):
  File "C:\Python37\Scripts\olemeta-script.py", line 11, in <module>
    load_entry_point('oletools==0.54.2', 'console_scripts', 'olemeta')()
  File "C:\Python37\lib\site-packages\oletools-0.54.2-py3.7.egg\oletools\olemeta.py", line 173, in main
    ole = olefile.OleFileIO(filename)
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1075, in __init__
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1192, in open
  File "C:\Python37\lib\site-packages\olefile-0.46-py3.7.egg\olefile\olefile.py", line 1105, in _raise_defect
OSError: not an OLE2 structured storage fil

**Comment by MalwareMechanic** [comment]
@opticoax747 Please check if the latest version of FLARE VM has fixed your issues.
