### ISSUE TITLE
Installation fails when installing visualstudio2017-workload-vctools

### ISSUE THREAD

**Issue by hashf0rd** [mandiant/flare-vm#581]
### What's the problem?

Following the standard installation instructions, the installation fails at the point of attempting to install visualstudio2017-workload-vctools . Cmd.exe hangs and the installation does not continue, and Cmd.exe has to be killed.

### Steps to Reproduce

1. Set up VM to meet requirements
2. Download install.ps1
3. Unblock script
4. Set execution to unrestriscted
5. Run install.ps1 as administrator
6. Continue installation until it fails

### Environment

Virtualization software: Virtualbox 7
VM OS: 10.0.19045
VM PowerShell: 5.1.19041.1682
VM Chocolatey: 2.2.2
VM Boxstarter: Boxstarter|3.0.3

**Output of VM-Get-Host-Info**

2024/04/02 15:35:45 vm.common.psm1 [+] INFO : Host Information

VM OS version and Service Pack
Version                 : 10.0.19045
BuildNumber             : 19045
OSArchitecture          : 64-bit
ServicePackMajorVersion : 0
Caption                 : Microsoft Windows 10 Enterprise Evaluation

VM OS RAM (MB)
0

VM OS HDD Space / Usage
DeviceID DriveType ProviderName VolumeName      Size        FreeSpace
C:       3                                      63804817408 36771123200
D:       5                      VBox_GAs_7.0.10 53497856    0

VM AV Details
AntiVirusProduct classname does not exist...

VM PowerShell Version
5.1.19041.1682

VM CLR Version
4.0.30319.42000

VM Chocolatey Version
2.2.2

VM Boxstarter Version
Boxstarter|3.0.3
Boxstarter.Bootstrapper|3.0.3
Boxstarter.Chocolatey|3.0.3
Boxstarter.Common|3.0.3
Boxstarter.HyperV|3.0.3
Boxstarter.WinConfig|3.0.3

VM Installed Packages
010editor.vm|14.0.0.20231204
7zip-15-05.vm|15.5.0.20231220
apimonitor|2.13.0.20210213
apimonitor.vm|2.13.0.20220224
apktool.vm|2.9.3
blobrunner.vm|0.0.5.20240217
blobrunner64.vm|0.0.5.20240217
Boxstarter|3.0.3
Boxstarter.Bootstrapper|3.0.3
Boxstarter.Chocolatey|3.0.3
Boxstarter.Common|3.0.3
Boxstarter.HyperV|3.0.3
Boxstarter.WinConfig|3.0.3
bytecodeviewer.vm|2.12.0
capa.vm|7.0.1
chocolatey|2.2.2
chocolatey-compatibility.extension|1.0.0
chocolatey-core.extension|1.4.0
chocolatey-dotnetfx.extension|1.0.1
chocolatey-visualstudio.extension|1.11.1
chocolatey-windowsupdate.extension|1.0.5
Cmder|1.3.24
cmder.vm|1.3.24.20240217
codetrack|1.0.3.301
codetrack.vm|1.0.3.20230526
common.vm|0.0.0.20240321
cyberchef.vm|10.8.2
de4dot-cex.vm|4.0.0.20230526
debloat.vm|0.0.0.20240321
dependencywalker|2.2.6000.9
dependencywalker.vm|2.2.6000
dex2jar.vm|2.3.0.20231025
didier-stevens-beta.vm|0.0.0.20240226
didier-stevens-suite.vm|0.0.0.20240226
die.vm|3.7.20240217
dll-to-exe.vm|1.1.0
dnlib.vm|4.0.0
dnspyex.vm|6.5.0
dotdumper.vm|1.1.0
DotNet3.5|3.5.20160716
dotnetfx|4.8.0.20220524
explorersuite.vm|0.0.0.20230925
extreme_dumper.vm|4.0.0.20240219
fakenet-ng.vm|1.4.11.20230418
file.vm|0.0.0.20240217
floss.vm|3.0.1.20240217
ghidra|11.0.1
ghidra.vm|11.0.1
googlechrome.vm|0.0.0.20240111
goresym.vm|2.4.0.20240217
hashmyfiles.vm|0.0.0.20240217
hollowshunter.vm|0.3.9
hxd|2.5.0
hxd.vm|2.5.0.20230925
installer.vm|0.0.0.20240305
KB2919355|1.0.20160915
KB2919442|1.0.20160915
KB2999226|1.0.20181019
KB3033929|1.0.5
KB3035131|1.0.3
openjdk|21.0.1
openjdk.vm|0.0.0.20240202
python3|3.10.11
python3.vm|0.0.0.20231019
python310|3.10.11
vcredist140|14.38.33135
vcredist2010|10.0.40219.32503
vcredist2015|14.0.24215.20170201
visualstudio2017buildtools|15.9.58
visualstudio2017-workload-vctools|1.3.3
visualstudio-installer|2.0.3

Common Environment Variables
VM_COMMON_DIR: C:\ProgramData\_VM
TOOL_LIST_DIR: C:\Users\FlareDev\Desktop\Tools
RAW_TOOLS_DIR: C:\Tools

### Additional Information

Console output at the time of the failed installation:
```
Progress: Downloading visualstudio2017-workload-vctools 1.3.3... 100%

visualstudio2017-workload-vctools v1.3.3 [Approved]
visualstudio2017-workload-vctools package files install completed. Performing other installation steps.
Installing visualstudio2017-workload-vctools...

[0770:0001][2024-04-02T15:28:50] Saving the current locale (en-US) to user.json.
[0770:0001][2024-04-02T15:28:50] Setting the telemetry services
[0770:0003][2024-04-02T15:28:50] Creating a new telemetry service.
[0770:0001][2024-04-02T15:28:50] Visual Studio Installer Version: 3.6.2122
[0770:0001][2024-04-02T15:28:50] Raw Command line: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --includeRecommended --norestart --quiet --add Microsoft.VisualStudio.Workload.VCTools
[0770:0001][2024-04-02T15:28:50] Parsed command line options: modify --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --norestart --quiet
[0770:0001][2024-04-02T15:28:51] Using registry value of (1) to theme installer.
[0770:0003][2024-04-02T15:28:51] Telemetry session ID: 39e710e7-d336-4ad1-98a8-e2ca39b248ff
[0770:0001][2024-04-02T15:28:51] Getting singleton lock. Mutex name: DevdivInstallerUI
[0770:0001][2024-04-02T15:28:51] Getting singleton lock succeed.
[0770:0003][2024-04-02T15:28:51] Creating new ExperimentationService
[0770:0003][2024-04-02T15:28:51] Telemetry property VS.ABExp.Flights : lazytoolboxinit;fwlargebuffer;refactoring;spmoretempsbtn1;asloff;keybindgoldbarext;asynccsproj;vsfricheditor;completionapi;typeimportcompletion:30562486;vsttkcf:30514304;87ce9466:30775294;i4588376:30751670;fijh5155:30690136;8ig0d248:30783238;85ihc887:30842123;chat_aa_t:30915623;treatment20240320:31006408;vscp_inline_gpt4_t:30966106;enablecontextinhistoryt:30979417;0604a212:30990143;gotodef_t:31006263
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.source : WPF
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.locale : en-US
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.installerversion : 3.6.2122.36397
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.startmethod : direct
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.activityid : c00fea8f-e36e-4f9d-bbca-5cae8bdeb993
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.campaign :
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.passive : False
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.quiet : True
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.processtype : ui
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.force : False
[0770:0003][2024-04-02T15:28:51] Telemetry property vs.willow.noweb : False
[0770:0001][2024-04-02T15:28:52] Navigation requested from ApplicationViewModel to MainPageViewModel
[0770:000d][2024-04-02T15:28:53] Telemetry property VS.SetupEngine.ChannelUpdateDisabled : False
Warning: [0770:000d][2024-04-02T15:28:53] Setup expects one or more channel manifest in the repository.
Warning: [0770:000d][2024-04-02T15:28:53] Setup expects one or more channel manifest in the repository.
[0770:000d][2024-04-02T15:28:53] Authentication Environment variable setting value: null
[0770:000f][2024-04-02T15:28:53] Download requested: https://aka.ms/vs/15/release/channel
[0770:0010][2024-04-02T15:28:54] Attempting download 'https://aka.ms/vs/15/release/channel' using engine 'WebClient'
[0770:0010][2024-04-02T15:28:54] Uri 'https://aka.ms/vs/15/release/channel' redirected to 'https://download.visualstudio.microsoft.com/download/pr/119c57b9-af7b-4970-81ff-824299902e62/c7f29d291d1026ca862aef41c12b4ace06dc70cffc96d569f22dbf545b4287e2/VisualStudio.15.Release.chman'
[0770:000e][2024-04-02T15:28:54] Uri 'https://go.microsoft.com/fwlink/?linkid=857708' redirected to 'https://sendvsfeedback2.azurewebsites.net/api'
[0770:0010][2024-04-02T15:28:54] ManifestVerifier Result: Success
[0770:0010][2024-04-02T15:28:54] Download of 'https://aka.ms/vs/15/release/channel' succeeded using engine 'WebClient'
[0770:000d][2024-04-02T15:28:54] Telemetry property vs.setup.WorkloadOverrides.DidReceiveOverride : False
[0770:000d][2024-04-02T15:28:54] Telemetry property vs.setup.WorkloadOverrides.RuleId : None
[0770:000a][2024-04-02T15:28:55] Trying to remove channel manifest: C:\Users\FlareDev\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\e22ce696\installChannelManifest.json
[0770:000a][2024-04-02T15:28:55] Trying to remove product manifest: C:\Users\FlareDev\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\e22ce696\install_catalog.json
Warning: [0770:000a][2024-04-02T15:28:55] No previous catalog found at 'C:\ProgramData\Microsoft\VisualStudio\Packages\_Instances\de50ed7f\catalog.previous.json'
[0770:000d][2024-04-02T15:28:55] Status changed to NoUpdate
[0770:000a][2024-04-02T15:28:55] Telemetry property VS.SetupEngine.ChannelUpdateDisabled : False
[0770:0010][2024-04-02T15:28:55] Download requested: https://go.microsoft.com/fwlink/?linkid=2066144
[0770:000f][2024-04-02T15:28:55] Attempting download 'https://go.microsoft.com/fwlink/?linkid=2066144' using engine 'WebClient'
Warning: [0770:000a][2024-04-02T15:28:55] Didn't find any channel feed.
[0770:000a][2024-04-02T15:28:55] Setup Engine v3.6.2122, Microsoft Windows NT 10.0.19045.0
[0770:000a][2024-04-02T15:28:55] Command line: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\setup.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --includeRecommended --norestart --quiet --add Microsoft.VisualStudio.Workload.VCTools
[0770:000f][2024-04-02T15:28:55] Uri 'https://go.microsoft.com/fwlink/?linkid=2066144' redirected to 'https://vsstartpagenewsfeed.azureedge.net/news/vs'
[0770:000f][2024-04-02T15:28:55] Download of 'https://go.microsoft.com/fwlink/?linkid=2066144' succeeded using engine 'WebClient'
[0770:000a][2024-04-02T15:28:55] Loading packages for instance 'de50ed7f'
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:56] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:57] DependencyComparer was created without a productArch. productArch will be ignored for dependency comparison.
[0770:000a][2024-04-02T15:28:57] Loaded existing instance for product 'Microsoft.VisualStudio.Product.BuildTools,version=15.9.34601.69'
[0770:000a][2024-04-02T15:28:57] Telemetry property VS.SetupEngine.Id : VisualStudio/15.9.60+34601.69
[0770:000a][2024-04-02T15:28:57] Telemetry property VS.SetupEngine.Branch : d15.9
[0770:000a][2024-04-02T15:28:57] Telemetry property VS.SetupEngine.BuildNumber : 15.9.34601.69
[0770:000a][2024-04-02T15:28:57] Telemetry property VS.SetupEngine.InstanceId : de50ed7f
[0770:000a][2024-04-02T15:28:57] Telemetry property VS.SetupEngine.EngineVersion : 3.6.2122.36397
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.UniversalCRT.Msu.8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.2,6.3)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.UniversalCRT.Msu.81 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.3,6.4)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.6.1.FullRedist.Threshold is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[10.0.10240]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.D3DCompiler.Msu.Win7 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.6.1.FullRedist.NonThreshold is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,6.4)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.UniversalCRT.Msu.7 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Store.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Store.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Desktop.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Desktop.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.7.FullRedist is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,10.0.14393]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.7.1.FullRedist is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,10.0.15063]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.7.2.FullRedist is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,10.0.16299]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '(,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.Debugger.DbgHelp.Win8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.UniversalCRT.Msu.8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.2,6.3)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.UniversalCRT.Msu.81 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.3,6.4)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.6.1.FullRedist.Threshold is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[10.0.10240]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.D3DCompiler.Msu.Win7 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.6.1.FullRedist.NonThreshold is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,6.4)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.UniversalCRT.Msu.7 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Store.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Store.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Desktop.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Windows.81SDK.Desktop.DirectX.Msi is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.7.FullRedist is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,10.0.14393]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.7.1.FullRedist is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,10.0.15063]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.Net.4.7.2.FullRedist is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1.1,10.0.16299]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '(,6.2)'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.Debugger.DbgHelp.Win8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8 is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.3]'.
[0770:000a][2024-04-02T15:28:57] Package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect is not applicable: The current OS Version '10.0.19045.0' is not in the supported version range '[6.1,6.2)'.
Warning: [0770:000a][2024-04-02T15:28:57] No previous catalog found at 'C:\ProgramData\Microsoft\VisualStudio\Packages\_Instances\de50ed7f\catalog.previous.json'
[0770:0016][2024-04-02T15:28:57] Adding packages from --add
[0770:0003][2024-04-02T15:28:57] Planning graph selection
[0770:0003][2024-04-02T15:28:57] Graph.PlanSelection completed in 4ms
[0770:0003][2024-04-02T15:28:57] Building the required chain
[0770:0003][2024-04-02T15:28:57] Committing graph selection
[0770:0003][2024-04-02T15:28:57] Graph.CommitSelection completed in 1ms
[0770:0003][2024-04-02T15:28:57] Updating graph selection
[0770:0003][2024-04-02T15:28:57] Graph.UpdateSelection completed in 2ms
[0770:0003][2024-04-02T15:28:57] Notifying VMs with the updated selections: GroupSelected - Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.VC.CoreBuildTools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.Redist.14.Latest Microsoft.VisualStudio.Component.Windows10SDK.17763 Microsoft.VisualStudio.Component.VC.CMake.Project Microsoft.VisualStudio.Component.TestTools.BuildTools Microsoft.VisualStudio.Component.Windows10SDK Microsoft.VisualStudio.Component.Static.Analysis.Tools
[0770:0003][2024-04-02T15:28:57] No restart manager available. Assuming no reboot required for instance state.
[0770:0003][2024-04-02T15:28:57] No restart manager available. Assuming no reboot required for instance state.
[0770:0011][2024-04-02T15:28:58] ManifestVerifier Result: Success
[0770:0011][2024-04-02T15:28:58] Creating a UnelevatedProductModifier to modify the following packages: Microsoft.VisualStudio.Product.BuildTools Microsoft.VisualStudio.Workload.MSBuildTools Microsoft.VisualStudio.Workload.VCTools Microsoft.VisualStudio.Component.Roslyn.Compiler Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.CoreBuildTools Microsoft.VisualStudio.Component.Windows10SDK Microsoft.VisualStudio.Component.VC.CoreBuildTools Microsoft.VisualStudio.Component.Static.Analysis.Tools Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.VC.Redist.14.Latest Microsoft.VisualStudio.Component.Windows10SDK.17763 Microsoft.VisualStudio.Component.VC.CMake.Project Microsoft.VisualStudio.Component.TestTools.BuildTools
[0770:0011][2024-04-02T15:28:58] Created a UnelevatedProductModifier
[0770:0011][2024-04-02T15:28:58] Decorating UnelevatedProductModifier with UnelevatedInstallerTelemetryDecorator
[0770:0011][2024-04-02T15:28:58] ManifestVerifier Result: Success
Warning: [0770:000d][2024-04-02T15:28:58] The operation was canceled.
Warning: [0770:0017][2024-04-02T15:28:58] Didn't find any channel feed.
Warning: [0770:000d][2024-04-02T15:28:58] Didn't find any channel feed.
[0770:001c][2024-04-02T15:28:58] WebClient error 'RequestCanceled' with 'https://aka.ms/vs/channels' - ExecuteWithRetryAsync failed along with a cancellation request
Warning: [0770:001c][2024-04-02T15:28:58] Failed to get the HttpWebResponse while invoking a HEAD request against https://aka.ms/vs/channels:System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.VisualStudio.Setup.Download.WebRequestService.<>c__DisplayClass9_0.<ExecuteWithRetryAsync>b__0(Object _)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Setup.Download.DownloadManagerAuthenticationProxy.<MungeUriAsync>d__29.MoveNext()
[0770:001c][2024-04-02T15:28:58] Download requested: https://aka.ms/vs/channels
Warning: [0770:001c][2024-04-02T15:28:58] Failed to download channels file from https://aka.ms/vs/channels: A task was canceled.
[0770:001e][2024-04-02T15:28:58] WebClient error 'RequestCanceled' with 'https://aka.ms/vs/installer/latest/feed' - ExecuteWithRetryAsync failed along with a cancellation request
Warning: [0770:001e][2024-04-02T15:28:58] Failed to get the HttpWebResponse while invoking a HEAD request against https://aka.ms/vs/installer/latest/feed:System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.VisualStudio.Setup.Download.WebRequestService.<>c__DisplayClass9_0.<ExecuteWithRetryAsync>b__0(Object _)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Setup.Download.DownloadManagerAuthenticationProxy.<MungeUriAsync>d__29.MoveNext()
[0770:001e][2024-04-02T15:28:58] Download requested: https://aka.ms/vs/installer/latest/feed
Warning: [0770:001e][2024-04-02T15:28:58] Failed to update the latest installer feed A task was canceled.
Warning: [0770:001e][2024-04-02T15:28:58] Didn't find any channel feed.
[0770:0016][2024-04-02T15:28:58] Status changed to NoUpdate
Warning: [0770:0018][2024-04-02T15:28:58] Didn't find any channel feed.
Warning: [0770:0016][2024-04-02T15:28:58] Didn't find any channel feed.
```

**Comment by Ana06** [comment]
I do not see that the package failed to install in that log. Can please share the whole log? Also, can you ensure you have an internet connection an run in a PowerShell console with admin rights (to see if you can install the package manually and ensure it is not a connection issue): `choco install visualstudio2017-workload-vctools`

**Comment by hashf0rd** [comment]
Oof now i feel silly - thank you for clarfying that this is not a sign the package installation failed, i took the WebClient exceptions to mean just that. The installation script did indeed hang for approx 10 mins at the point you can see in the above log (where the webclient exceptions are thrown) but after that it continues just fine. I was clearly being too impatient. Thanks for clearing that up and sorry for wasting your time, this issue can be closed.
